/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;

/**
 *
 * @author TRI
 */
public class HomeAdmin extends javax.swing.JFrame {

    /**
     * @return the btnInputKasir
     */
    public javax.swing.JButton getBtnInputKasir() {
        return btnInputKasir;
    }

    /**
     * @param btnInputKasir the btnInputKasir to set
     */
    public void setBtnInputKasir(javax.swing.JButton btnInputKasir) {
        this.btnInputKasir = btnInputKasir;
    }

    /**
     * @return the btnInputPembeli
     */
    public javax.swing.JButton getBtnInputPembeli() {
        return btnInputPembeli;
    }

    /**
     * @param btnInputPembeli the btnInputPembeli to set
     */
    public void setBtnInputPembeli(javax.swing.JButton btnInputPembeli) {
        this.btnInputPembeli = btnInputPembeli;
    }

    /**
     * @return the btnLihatPembeli
     */
    public javax.swing.JButton getBtnLihatPembeli() {
        return btnLihatPembeli;
    }

    /**
     * @param btnLihatPembeli the btnLihatPembeli to set
     */
    public void setBtnLihatPembeli(javax.swing.JButton btnLihatPembeli) {
        this.btnLihatPembeli = btnLihatPembeli;
    }

    /**
     * @return the btnLihatkasir
     */
    public javax.swing.JButton getBtnLihatkasir() {
        return btnLihatkasir;
    }

    /**
     * @param btnLihatkasir the btnLihatkasir to set
     */
    public void setBtnLihatkasir(javax.swing.JButton btnLihatkasir) {
        this.btnLihatkasir = btnLihatkasir;
    }

    /**
     * @return the btnLogout
     */
    public javax.swing.JButton getBtnLogout() {
        return btnLogout;
    }

    /**
     * @param btnLogout the btnLogout to set
     */
    public void setBtnLogout(javax.swing.JButton btnLogout) {
        this.btnLogout = btnLogout;
    }

    /**
     * Creates new form Admin
     */
    public HomeAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnInputKasir = new javax.swing.JButton();
        btnInputPembeli = new javax.swing.JButton();
        btnLihatkasir = new javax.swing.JButton();
        btnLihatPembeli = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jLabel1.setText("Admin");

        btnInputKasir.setText("Input Kasir");
        btnInputKasir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInputKasirActionPerformed(evt);
            }
        });

        btnInputPembeli.setText("Input Pembeli");
        btnInputPembeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInputPembeliActionPerformed(evt);
            }
        });

        btnLihatkasir.setText("Lihat Kasir");
        btnLihatkasir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLihatkasirActionPerformed(evt);
            }
        });

        btnLihatPembeli.setText("Lihat Pembeli");
        btnLihatPembeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLihatPembeliActionPerformed(evt);
            }
        });

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnInputPembeli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnInputKasir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnLihatPembeli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnLihatkasir, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(54, 54, 54))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(165, 165, 165))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInputKasir)
                    .addComponent(btnLihatkasir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInputPembeli)
                    .addComponent(btnLihatPembeli))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInputKasirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInputKasirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInputKasirActionPerformed

    private void btnInputPembeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInputPembeliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInputPembeliActionPerformed

    private void btnLihatkasirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLihatkasirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLihatkasirActionPerformed

    private void btnLihatPembeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLihatPembeliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLihatPembeliActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Admin().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInputKasir;
    private javax.swing.JButton btnInputPembeli;
    private javax.swing.JButton btnLihatPembeli;
    private javax.swing.JButton btnLihatkasir;
    private javax.swing.JButton btnLogout;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
    public void addActionListener(ActionListener e) {
        this.btnInputKasir.addActionListener(e);        
        this.btnLihatPembeli.addActionListener(e);        
        this.btnLihatkasir.addActionListener(e);  
        this.btnInputPembeli.addActionListener(e);
        this.btnLogout.addActionListener(e);  
    }
}
