/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;

/**
 *
 * @author TRI
 */
public class HomeKasir extends javax.swing.JFrame {

    /**
     * Creates new form HomeKasir
     */
    public HomeKasir() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnInputTransaksi = new javax.swing.JButton();
        btnInputObat = new javax.swing.JButton();
        btnLihatTransaksi = new javax.swing.JButton();
        btnLihatObat = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnInputTransaksi.setText("Input Transaksi");

        btnInputObat.setText("Input Obat");
        btnInputObat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInputObatActionPerformed(evt);
            }
        });

        btnLihatTransaksi.setText("Lihat Transaksi");
        btnLihatTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLihatTransaksiActionPerformed(evt);
            }
        });

        btnLihatObat.setText("Lihat Obat");
        btnLihatObat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLihatObatActionPerformed(evt);
            }
        });

        btnLogout.setText("Logout");

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jLabel1.setText("Home Kasir");

        jLabel2.setText("ID");

        jLabel3.setText("Nama");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnLogout)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnInputTransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnInputObat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(30, 30, 30)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnLihatTransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnLihatObat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(81, 81, 81)
                            .addComponent(jLabel1))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(41, 41, 41)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2)))))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInputTransaksi)
                    .addComponent(btnLihatTransaksi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInputObat)
                    .addComponent(btnLihatObat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInputObatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInputObatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInputObatActionPerformed

    private void btnLihatTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLihatTransaksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLihatTransaksiActionPerformed

    private void btnLihatObatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLihatObatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLihatObatActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(HomeKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(HomeKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(HomeKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(HomeKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new HomeKasir().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInputObat;
    private javax.swing.JButton btnInputTransaksi;
    private javax.swing.JButton btnLihatObat;
    private javax.swing.JButton btnLihatTransaksi;
    private javax.swing.JButton btnLogout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the btnInputObat
     */
    public javax.swing.JButton getBtnInputObat() {
        return btnInputObat;
    }

    /**
     * @param btnInputObat the btnInputObat to set
     */
    public void setBtnInputObat(javax.swing.JButton btnInputObat) {
        this.btnInputObat = btnInputObat;
    }

    /**
     * @return the btnInputTransaksi
     */
    public javax.swing.JButton getBtnInputTransaksi() {
        return btnInputTransaksi;
    }

    /**
     * @param btnInputTransaksi the btnInputTransaksi to set
     */
    public void setBtnInputTransaksi(javax.swing.JButton btnInputTransaksi) {
        this.btnInputTransaksi = btnInputTransaksi;
    }

    /**
     * @return the btnLihatObat
     */
    public javax.swing.JButton getBtnLihatObat() {
        return btnLihatObat;
    }

    /**
     * @param btnLihatObat the btnLihatObat to set
     */
    public void setBtnLihatObat(javax.swing.JButton btnLihatObat) {
        this.btnLihatObat = btnLihatObat;
    }

    /**
     * @return the btnLihatTransaksi
     */
    public javax.swing.JButton getBtnLihatTransaksi() {
        return btnLihatTransaksi;
    }

    /**
     * @param btnLihatTransaksi the btnLihatTransaksi to set
     */
    public void setBtnLihatTransaksi(javax.swing.JButton btnLihatTransaksi) {
        this.btnLihatTransaksi = btnLihatTransaksi;
    }

    /**
     * @return the btnLogout
     */
    public javax.swing.JButton getBtnLogout() {
        return btnLogout;
    }

    /**
     * @param btnLogout the btnLogout to set
     */
    public void setBtnLogout(javax.swing.JButton btnLogout) {
        this.btnLogout = btnLogout;
    }
    
    public void addActionListener(ActionListener e) {
        this.btnInputObat.addActionListener(e);  
        this.btnInputTransaksi.addActionListener(e);  
        this.btnLihatObat.addActionListener(e);  
        this.btnLihatTransaksi.addActionListener(e);  
        this.btnLogout.addActionListener(e);  
    }
}
